- name: enable services
  service:
    name: "{{ item }}"
    state: started 
    enabled: yes
  with_items:
    - avahi-daemon.service
    - org.cups.cupsd.service
    - lightdm.service
    - systemd-timesyncd.service

      #- name: 'Enable PSD'
      #  command: systemctl --global disable psd.service
      #  ignore_errors: yes

# should create this directroy or check if mathematica is installed
- name: Configure mathematica license servers
  template:
    src: mathpass.j2
    dest: /opt/Mathematica/Configuration/Licensing/mathpass
    mode: 0755

- name: pacman updated
  set_fact:
    pacman_old: "false"

