- name: set locale(s)
  locale_gen:
    name: "{{ item }}"
    state: present
  loop: "{{ system.locales }}"


  #Users & security
- name: Setup sudoers
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) ALL'
    validate: '/usr/bin/visudo -cf %s'

- name: Setup sudo groups
  lineinfile:
    path: /etc/sudoers.d/{{ brand.short }}
    state: present
    create: yes
    insertafter: EOF
    line: '%{{item}} ALL=(ALL:ALL) ALL'
    validate: '/usr/bin/visudo -cf %s'
  loop: "{{ sudo.groups }}"


  #TODO: cleanup / use loops - move maybe?
  #TODO: create generic role for desktop entries
- name: Setup usr/local/bin
  block:
    copy: src=usr dest=/
    template: src=usr-local-bin-zdrive.j2 dest=/usr/local/bin/zdrive mode=0766
    template: src=entry.desktop.j2 dest=/usr/share/applications/zdrive.desktop


