- name: Install tower-cli
  pacman: name=tower-cli state=present update_cache=yes 

- name: Setup AWX oragizations
  tower_organization:
    name: {{ awx.org }}
    description: {{ awx.description }} 
    state: present
    tower_config_file: /root/.tower_cli.cfg

- name: create playbook/git mountpoint
  file:
    path: "{{ build.git.dest }}"
    state: directory

- name: Mount playbooks git repo
  include_role:
    name: ypsman.systemd_mounts
  vars:
    mounts:
      git:
        share: "{{ build.git.src }}"
        mount: "{{ build.git.dest }}"
        type: cifs
        options: "credentials={{ cifs.creds.dest }},iocharset=utf8,rw,x-systemd.automount,noauto,fsc,vers={{ cifs.vers }},forceuid,forcegid,uid={{build.user.uid}},gid={{build.user.gid}},mfsymlinks,nobrl"
        automount: true

- name: Add credentials for git repo
  tower_credential:
    name: "awx host"
    organization: CCIT
    kind: scm
    #    project: playbooks
    ssh_key_data: "{{ lookup('file', '/home/josh/.ssh/id_rsa_mines') }}"
    tower_config_file: /root/.tower_cli.cfg


- name: Add SSH creds for build server(s)
  tower_credential:
    name: "build server"
    organization: CCIT
    kind: ssh 
    #    project: playbooks
    ssh_key_data: "{{ lookup('file', '/home/josh/.ssh/id_rsa_mines') }}"
    tower_config_file: /root/.tower_cli.cfg

- name: Setup playbooks project
  tower_project:
    name: {{ awx.project.name }} 
    scm_credential: {{ awx.project.scm_credential }}
    description: {{ awx.project.description }}
    organization: {{ awx.project.CCIT }}
    state: present
    scm_type: git
    scm_url: "{{ awx.project.url }}"
    tower_config_file: /root/.tower_cli.cfg

- name: setup AWX inventory
  tower_inventory:
    tower_config_file: /root/.tower_cli.cfg
    name: Lab
    organization: CCIT
    state: present

