- name: sshd - install openSSH
  pacman: name=openssh state=present

- name: Copy authorized keys to account(s)
  authorized_key:
    user: "{{ item.user }}" 
    state: "{{ item.state }}"
    key: "{{ item.key }}"
  loop: "{{ ssh1.ceys|flatten(levels=1) }}"
  #loop: "{{ q('list', ssh.root.keys) }}"
  
- name: sshd - configure 
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - {src: 'sshd_config.j2', dest: '/etc/ssh/sshd_config' }
    - {src: 'ssh_config.j2', dest: '/etc/ssh/ssh_config' }

- name: sshd - prefer socket
  block:
    - name: sshd - disable service
      service: name=sshd.service state=stopped enabled=no
    - name: sshd - enable socket
      service: name=sshd.socket state=started enabled=yes

- name: sshd - populate system known_hosts
  copy: src=known_hosts dest=/etc/ssh/ssh_known_hosts
