- name: Copy authorized keys to account(s)
  authorized_key:
    user: "{{ item.user }}" 
    state: present
    key: "{{ item.key }}"
  loop: "{{ ssh1.ceys|flatten(levels=1) }}"
  #loop: "{{ q('list', ssh.root.keys) }}"
  
- name: Configure SSHd on labs and servers
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - {src: 'sshd_config.j2', dest: '/etc/ssh/sshd_config' }
    - {src: 'ssh_config.j2', dest: '/etc/ssh/ssh_config' }

- name: Disable sshd.service
  service: 
    name: sshd.service
    state: stopped
    enabled: no

- name: Enable sshd socket
  service:
    name: sshd.socket
    state: started
    enabled: yes

- name: populate system known_hosts
  copy: src=known_hosts dest=/etc/ssh/ssh_known_hosts
