- name: enable services
  service:
    name: "{{ item }}"
    state: started 
    enabled: yes
  with_items:
    - sssd.service

    
- name: pacman updated
  set_fact:
    pacman_old: "false"

- name: Add and sign sublime key, and populate pacman keyring
  command: '{{item}}'
  with_items:
          - 'pacman-key --add /etc/pacman.d/sublimehq-pub.gpg'
          - 'pacman-key --lsign-key 8A8F901A'
          - 'pacman-key --populate'

