---
- name: Copy Secure Boot Key and CRT
  block:
    - name: secure boot - copy secureboot filder
      copy: src=etc/secureboot dest=/etc/ owner=root group=root mode=0600
    - name: secure boot - what?
      copy: src=etc/pacman.d dest=/etc/ owner=root group=root
    - name: secure boot - copy boot files
      copy: src=boot/client dest=/boot/ owner=root group=root mode=0600
    - name: secure boot - template sbupdate
      template: src=sbupdate.j2 dest=/etc/default/sbupdate
    - name: secure boot - install sbupdate-git
      pacman: name=sbupdate-git state=present update_cache=yes
    - name: secure boot - install fwupd
      pacman: name=fwupd state=present update_cache=yes
    - name: secure boot - template uefi
      template: src=uefi.conf.j2 dest=/etc/fwupd/uefi.conf
    - name: secure boot - run sbupdate
      shell: /usr/bin/sbupdate
    - name: secure boot - enable fwupd
      systemd: name=fwupd.service state=restarted
    - name: secure boot - delete old boot entries (MOVE)
      shell: /usr/bin/efibootmgr -B -b "{{ item }}"
      loop: "{{ range(0, 6, 1)|list }}"
      ignore_errors: true
