- name: Install background logo png
  copy:
    src: background.png
    dest: /usr/share/pixmaps/background.png
    owner: root
    group: root
    mode: 0644
  notify:
    - enable services
  when: isgui|bool
