servers:
  hosts:
    plabnagios
    plabpuppet
  build:
    hosts:
      labbuild-test1
      labbuild-test2
      labbuild-test3
lab:
  labservers:
    hosts:
      isengard
  classrooms:
    bb136:
      hosts:
        bb136-[01:24]
    ch215l:
      hosts:
        ch215li
        ch215l-[01:16]
    ch275l:
      hosts:
        ch275l-[01:08]
    ck182:
      hosts:
        ck182-[18:34]
    grla110:
      hosts:
        grla110i
        grla110-[01:28]
