- name: Install packages for libvirtd, qemu, and lxc
  pacman:
      name: "{{ libvirtd_packages  + lxc_packages  + qemu_packages }}"
      state: latest
      update_cache: yes
      #  with_flattened:
  notify:
    - 'Restart libvirtd'

- name: Make sure local facts dir exists
  file:
    path: '/etc/ansible/facts.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'
