- name: enable services
  service:
    name: "{{ item }}"
    state: started 
    enabled: yes
  with_items:
    - avahi-daemon.service
    - org.cups.cupsd.service
    - lightdm.service
    - sssd.service
    - systemd-timesyncd.service

      #- name: 'Enable PSD'
      #  command: systemctl --global disable psd.service
      #  ignore_errors: yes
    
- name: Configure mathematica license servers
  copy:
    src: mathpass
    dest: /opt/Mathematica/Configuration/Licensing/mathpass
    mode: 0755
  ignore_errors: true

- name: pacman updated
  set_fact:
    pacman_old: "false"

