- name: Check if pacman keyring is present
  stat: path='/etc/pacman.d/gnupg/trustdb.gpg'
  register: pacmankeyring

- name: Populate pacman keyring
  block:
    - shell: "pacman-key --init"
    - shell: "pacman-key --populate"
  when: pacmankeyring.stat.exists != true

# Attempt to use signing name as destination name
- name: Fetch, import, and trust sumblime key
  block:
    - get_url: url="{{ item.src }}" dest="/etc/pacman.d/{{ item.name }}"
    - shell: "pacman-key --add /etc/pacman.d/{{ item.name }}"
    - shell: "pacman-key --lsign-key {{ item.name }}"
  when: item.src is defined

- name: Import pacman keys
  include: key.yml
  when: item.src is not defined

