- name: deploy mirrors.conf and mirrorlist
  block:
    - template: src=mirrors.conf.j2 dest=/etc/pacman.d/mirrors.conf
    - copy: src=mirrorlist dest=/etc/pacman.d/mirrorlist

- import_tasks: pacserve.yml
  tags: [pacserve]

- include_tasks: gpg.yml
  loop: "{{ pacmankeys|flatten(levels=1) }}"
  tags: [pacmankey]
  
- name: Setup pacman.conf
  template:
    src: pacman.conf.j2
    dest: /etc/pacman.conf
  ignore_errors: yes

- name: Create pacman.d hook folder
  file:
    path: /etc/pacman.d/hooks
    state: directory
    owner: root
    
- name: Setup paccache hook
  copy:
    src: paccache.hook
    dest: /etc/pacman.d/hooks/paccache.hook
