# Pacserve
- name: deploy mirrors.conf and mirrorlist
  block:
    - template: src=mirrors.conf.j2 dest=/etc/pacman.d/mirrors.conf
    - copy: src=mirrorlist dest=/etc/pacman.d/mirrorlist

  # update pacman.conf template to only include existing /etc/pacman.d/* conf files
- import_tasks: pacserve.yml
  tags: [pacserve]

- include_tasks: gpg.yml
  loop: "{{ pacmankeys|flatten(levels=1) }}"
  tags: [pacmankey]
  
- name: Setup initial pacman.conf
  template:
    src: pacman.conf.j2
    dest: /etc/pacman.conf
  ignore_errors: yes

- name: Create pacman.d hook folder
  file:
    path: /etc/pacman.d/hooks
    state: directory
    owner: root
    
- name: Setup paccache hook
  copy:
    src: paccache.hook
    dest: /etc/pacman.d/hooks/paccache.hook


# Not sure where to put this stuff
# ------------------------------

#TODO: move these to specific roles
- name: install packages for ldap/kerboros, dell configure
  pacman:
    name: dell-command-configure, ufw
    state: present 

- name: avahi
  pacman:
    name: avahi, nss-mdns
    state: present
  notify: enable services
  when: isgui|bool

- name: printing support
  pacman:
    name: cups, gtk3 cups-pdf
    state: present
  notify: enable services

- name: enable and (re)start services
  command: echo
  notify: enable services
