- name: Setup pacman.conf
  template:
    src: pacman.conf.j2
    dest: /etc/pacman.conf
    #  ignore_errors: yes

- name: deploy mirrors.conf and mirrorlist
  block:
    - template: src=mirrors.conf.j2 dest=/etc/pacman.d/mirrors.conf
    - copy: src=mirrorlist dest=/etc/pacman.d/mirrorlist

- include_tasks: gpg.yml
  loop: "{{ pacmankeys|flatten(levels=1) }}"
  tags: [pacmankey]
  
- import_tasks: pacserve.yml
  tags: [pacserve]

- name: pacman hooks
  block:
    - name: pacman hooks - create folder
      file: path=/etc/pacman.d/hooks state=directory owner=root
    - name: pacman hooks - copy hook(s)
      copy: src={{ item }} dest='/etc/pacman.d/hooks/'
      loop:
        - paccache.hook
        - linux-modules-post.hook
        - linux-modules-pre.hook
    - name: pacman hooks - supporting file(s)
      copy: src='linux-modules-cleanup.service' dest='/etc/systemd/system/'
    - name: pacman hooks - supporting service(s)
      systemd: name=linux-modules-cleanup.service state=started enabled=true




