- name: Set lightdm config files
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: root
    group: root
    mode: 0644
  with_items:
     - {src: 'lightdm-gtk-greeter.conf', dest: '/etc/lightdm/lightdm-gtk-greeter.conf'}
     - {src: 'lightdm.conf', dest: '/etc/lightdm/lightdm.conf'}  
  notify:
    - enable services
  when: isgui|bool

    
- name: Install mathematica license file
  block:
    - file: path=/opt/Mathematica/Configuration/Licensing/ state=directory
    - copy: src=mathpass dest=/opt/Mathematica/Configuration/Licensing/mathpass
  ignore_errors: yes
  when: islab|bool

