- name: configure network
  template:
    src: '{{ item }}'
    dest: '/etc/systemd/network/'
    owner: root
    group: root
    mode: 0644
  loop: "{{ network.config |flatten(levels=1) }}"
  
- name: setup systemd based resolv.conf
  file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: yes
