- name: Setup buildserver 
  hosts: labbuild 
  strategy: free
  gather_facts: True
  become: yes
  roles:
    - {role: buildserver, tags: ['buildserver']}
    - role: ypsman.systemd_mounts 
      mounts:
        aursync:
          share: "{{ build.aur.src }}"
          mount: "{{ build.aur.dest }}"
          type: cifs
          options: "credentials={{ cifs.creds.dest }},iocharset=utf8,rw,x-systemd.automount,noauto,fsc,vers={{ cifs.vers }},forceuid,forcegid,uid={{build.user.uid}},gid={{build.user.gid}},mfsymlinks,nobrl"
          automount: true
        repo:
          share: "{{ build.repo.src }}"
          mount: "{{ build.repo.dest }}"
          type: cifs
          options: "credentials={{ cifs.creds.dest }},iocharset=utf8,rw,x-systemd.automount,noauto,fsc,vers={{ cifs.vers }},forceuid,forcegid,uid={{build.user.uid}},gid={{build.user.gid}},mfsymlinks,nobrl"
          automount: true
      tags:
        - mounts
    - {role: robertdebock.httpd, tags: ['httpd'] }
    - {role: server_sensu, tags: ['server_sensu']}
    - {role: ldap, tags: ['ldap']}
    - {role: tftp, tags: ['tftp']}
    - {role: root, tags: ['root']}
    - {role: archmirror, tags: ['archmirror']}
    - {role: awx, tags: ['awx']}
