- name: Post install config 
  hosts: all 
  strategy: free
  gather_facts: True
  vars:
    isdell: true
    sensu:
      rabbitmq:
        host: plabmon.mines.edu
        user: "client"
        password: "sm2JNjS6lhGjKnPFnp5w" 
    zsh:
      theme: clint
      term: linux
    contact_email: jhoffer@mines.edu
    mines_repo_host: greyfox.mines.edu:15678
    type: lab
    repos:
      mines2:
        server: labbuild-test1.mines.edu
    sudoers:
      - ccitlabadmins
    module_list:
      - nfs
      - cachefiles
    pacmankeys:
      - {name: "8A8F901A", src: "https://download.sublimetext.com/sublimehq-pub.gpg"}
      - {name: "7448C890582975CD" }
    ldap:
      packages: openldap, nss-pam-ldapd, sssd, pam-krb5, pacserve
      domains: mines.edu
      uri: "ldaps://ldap.mines.edu"
      searchbase: "dc=mines,dc=edu"
      tlscacert_src: MinesCerts
      tlscacert_dir: "/etc/MinesCerts"
      realm: "MINES.EDU"
      krb5_server: "138.67.138.105,138.67.138.106"
      sssd:
        config_src: sssd.conf.j2
        config_dst: /etc/sssd/sssd.conf
  pre_tasks:
    - pacman: update_cache=true
      register: pacman_updated

  roles:
    - {role: common, tags: ['common']}
    - {role: pacman, tags: ['pacman']}
    - {role: sensu , tags: ['sensu']}
    - {role: ldap, tags: ['ldap']}
    #- {role: virt, tags: ['virt']}
    - {role: ipfs, tags: ['ipfs']}
    - {role: root, tags: ['root']}
    # upgrade (software install) takes the longest
    - {role: upgrade, tags: ['upgrade']}
    - {role: bios, tags: ['bios']}
    - {role: secureboot, tags: ['secureboot']}
