- name: Post install config 
  hosts: all 
  strategy: free
  gather_facts: True
  vars:
    brand:
      short: csm
    system:
      locales:
        - en_US.UTF-8
        - en_DK.UTF-8
    ssh:
      root:
        sshkeys: rootkeys
        user: root
    lightdm:
      session-wrapper: /etc/lightdm/Xsession
      session-cleanup: /etc/lightdm/Xcleanup
    isdell: true
    sensu:
      rabbitmq:
        host: plabmon.mines.edu
        user: "client"
        password: "sm2JNjS6lhGjKnPFnp5w" 
    zsh:
      theme: clint
      term: linux
    contact_email: jhoffer@mines.edu
    mines_repo_host: greyfox.mines.edu:15678
    type: lab
    repos:
      mines2:
        server: labbuild-test1.mines.edu
    sudo:
      groups:
        - ccitlabadmins
    # REMOVE module_list
    module_list:
      - cachefiles
    pacmankeys:
      - {name: "8A8F901A", src: "https://download.sublimetext.com/sublimehq-pub.gpg"}
      - {name: "7448C890582975CD" }
    nfs:
      domain: mines.edu
    ldap:
      packages:
        - openldap
        - nss-pam-ldapd
        - sssd
        - pam-krb5
      domains: mines.edu
      uri: "ldaps://ldap.mines.edu"
      searchbase: "dc=mines,dc=edu"
      tlscacert_src: MinesCerts
      tlscacert_dir: "/etc/MinesCerts"
      realm: "MINES.EDU"
      krb5_server: "138.67.138.105,138.67.138.106"
      sssd:
        config_src: sssd.conf.j2
        config_dst: /etc/sssd/sssd.conf
    network:
      - 25-wired.network
    mounts:
      home:
        share: files.mines.edu:/export/fermat
        mount: /u 
        type: nfs
        options: auto,x-systemd.automount,x-systemd.device-timeout=10,rsize=32768,wsize=32768,nolock,ac,vers=3
        automount: true
      gpfc:
        share: files.mines.edu:/export/gpfc
        mount: /gpfc 
        type: nfs
        options: auto,x-systemd.automount,x-systemd.device-timeout=10,rsize=32768,wsize=32768,nolock,ac,vers=3
        automount: true
      scratch:
        share: files.mines.edu:/export/scratch
        mount: /scratch 
        type: nfs
        options: auto,x-systemd.automount,x-systemd.device-timeout=10,rsize=32768,wsize=32768,nolock,ac,vers=3
        automount: true
  pre_tasks:
    - pacman: update_cache=true
      register: pacman_updated

  roles:
    - {role: common, tags: ['common']}
    - {role: system, tags: ['system']}
    - {role: mount, tags: ['mount']}
    - {role: pacman, tags: ['pacman']}
    - {role: sensu , tags: ['sensu']}
    - {role: ldap, tags: ['ldap']}
    - {role: ansible, tags: ['ansible']}
    #- {role: virt, tags: ['virt']}
    - {role: ipfs, tags: ['ipfs']}
    - {role: root, tags: ['root']}
    # upgrade (software install) takes the longest
    - {role: upgrade, tags: ['upgrade']}
    - {role: bios, tags: ['bios']}
    - {role: secureboot, tags: ['secureboot']}
