- name: Setup iPXE server 
  hosts: labbuild
  #hosts: localhost
  #strategy: free
  #gather_facts: True
  become: yes 
  vars:
    arch:
      key: "/tmp/sb.key"
      key_src: "/data/sb/DB.key"
      crt_src: "/data/sb/DB.crt"
      crt: "/tmp/sb.crt"
      mkosi:
        repo: "https://github.com/JoshH100/archlive-mkosi.git"
        dest: "/data/mkosi"
        output: "/data/arch/"
        iso:
          start1: 1048576
          root1: 269484032
    secureboot:
      cert: "/etc/secureboot/DB.crt"
      key: "/etc/secureboot/DB.key"
    atftp:
      args: "--no-multicast --maxthread 20 --verbose=6 /mnt/arch"
    ipxe:
      dest: /mnt/arch
      fs: /mnt/fs
      images:
        live:
          src: /data/files/CCIT/linux/images/arch/root/root/archinstall
          dest: /mnt/archinstall.tar.gz
        archlinux:
          linux:
            src: archlinux/linux
            dest: linux
          initrd:
            src: archlinux/initrd
            dest: initrd
          rootfs:
            src: archlinux/airootfs.sfs
            dest: fs/x86_64/airootfs.sfs 
      release: 1
      extrabootoptions: ip=dhcp net.ifnames=0 BOOTIF=01-${netX/mac} modprobe.blacklist=nouveau
      countrycode: US
      ccit:
        mirrorurl: http://labbuild-test1.mines.edu:3000/
        backgroundurl: http://labbuild-test1.mines.edu:3000/windows95.jpg
      menu:
        title: CCIT Archlinux Deployer
  roles:
    - {role: ipxe, tags: ['ipxe']}
