- name: Post install config for lab machines
  hosts: lab
  strategy: free
  gather_facts: True
  pre_tasks:
    - pacman: update_cache=true
      register: pacman_updated
    - name: check if paserve is installed
      shell: pacman -Q pacserve
      register: pac_pacserve
      ignore_errors: true
  roles:
    - {role: ssh, tags: ['ssh']}
    - {role: mlocate, tags: ['mlocate']}
    - {role: system, tags: ['system']}
    - {role: mount, tags: ['mount']}
    - {role: pacman, tags: ['pacman']}
    - {role: sensu , tags: ['sensu']}
    - {role: ldap, tags: ['ldap']}
    - {role: ansible, tags: ['ansible']}
    - {role: root, tags: ['root']}
    - {role: bios, tags: ['bios']}
    - {role: secureboot, tags: ['secureboot']}
    - {role: network , tags: ['network']}
    - {role: ldap, tags: ['ldap']}
    - {role: graphical, tags: ['graphical']}
    # upgrade (software install) takes the longest
    - {role: upgrade, tags: ['upgrade']}
