- name: Required roles
  block:
    - include_role: name=network

- name: install packages for ldap/kerboros
  pacman:
    name: "{{ ldap.packages }}"
    state: latest

- name: configure certs for ldap
  copy:
    src: "{{ ldap.tlscacert_src }}"
    dest: "{{ ldap.tlscacert_dir }}"
    owner: root
    group: root
    mode:  0644

- name: copy lab specific config files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {src: 'lightdm', dest: '/etc/pam.d/lightdm'}
    #    - {src: 'lightdm.conf', dest: '/etc/lightdm/lightdm.conf'}
  when: (type == "lab") and (isgui | bool)

- name: configure pam, nsswitch, sshd 
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - {src: 'nsswitch.conf', dest: '/etc/nsswitch.conf'}
    - {src: 'system-auth', dest: '/etc/pam.d/system-auth'}
    - {src: 'nscd.conf', dest: '/etc/nscd.conf'}
    - {src: 'passwd', dest: '/etc/pam.d/passwd'}
    - {src: 'nobeep.conf', dest: '/etc/modprobe.d/nobeep.conf'} #MOVE 
    - {src: 'sssd.service', dest: '/etc/systemd/system/'}
    - {src: 'waitnetwork.conf', dest: '/etc/systemd/system/sssd.service.d/'}

- name: configrure sssd, krb5
  template:
    src: '{{ item.src }}' 
    dest: '{{ item.dest }}' 
    mode: 0644
  with_items:
    - {src: 'ldap.conf.j2', dest: '/etc/openldap/ldap.conf' } 
    - {src: 'sssd.conf.j2', dest: '/etc/sssd/sssd.conf' } 
    - {src: 'krb5.conf.j2', dest: '/etc/krb5.conf'}  
  notify: enable sssd

- name: configure krb5 and keytab
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: root
    group: root
    mode: 0600
  ignore_errors: yes
  with_items:
    - {src: "keytabs/krb5.keytab.{{ansible_hostname}}", dest: '/etc/krb5.keytab' }

- name: set timezone
  timezone:
    name: "{{ system.timezone }}"

- name: start and enable sssd and timesyncd
  service:
    name: "{{ item }}"
    state: started 
    enabled: yes
  loop: 
    - sssd.service
    - systemd-timesyncd
