---
#TODO: move to other roles...
- name: config files 
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: root
    group: root
    mode: 0644
  with_items:
     - {src: 'logind.conf', dest: '/etc/systemd/logind.conf' }
     - {src: '40-max-user-watches.conf', dest: '/etc/sysctl.d/40-max-user-watches.conf'}  
