- name: update cache
  pacman:
    update_cache: yes
  ignore_errors: yes
 
- name: Remove software
  package:
      name: "{{ item }}"
      state: absent
  ignore_errors: yes 
  with_flattened:
    - "{{ software_remove }}"

- name: Install software
  package:
      name: "{{ item }}"
      state: present
  ignore_errors: no 
  with_flattened:
    - "{{ software}}"
