- name: update cache
  pacman:
    update_cache: yes
  ignore_errors: yes

- name: install lzop for lzop compressed packages
  pacman: name=lzop state=present 

- name: Remove software
  package:
      name: "{{ item }}"
      state: absent
  ignore_errors: yes 
  loop:
    - "{{ packages_remove }}"

- name: Install software
  package:
      name: "{{ item }}"
      state: present
  ignore_errors: no 
  loop:
    - "{{ packages_install }}"
