- name: Check for NVIDIA card
  shell: "lspci | grep VGA" 
  register: vga_devices_output
  ignore_errors: true
  when: isgui|bool
 
- name: print contains AMD card debug
  debug: msg="Contains AMD Card"
  when:
    - (vga_devices_output.stdout.find('AMD') != -1) and
    - (isgui|bool)

- name: print contains NVIDIA card debug
  debug: msg="Contains NVIDIA Card"
  when:
    - (vga_devices_output.stdout.find('NVIDIA') != -1)
    - (isgui|bool)

- name: Install NVIDIA driver
  pacman:
    name: nvidia,nvidia-utils,lib32-nvidia-utils
    state: latest
  when:
    - (vga_devices_output.stdout.find('NVIDIA') != -1)
    - (isgui | bool)


- name: Install AMD driver
  pacman:
    name: xf86-video-amdgpu,mesa,lib32-mesa,vulkan-radeon,lib32-vulkan-radeon,libva-mesa-driver,lib32-libva-mesa-driver,mesa-vdpau,lib32-mesa-vdpau
    state: latest
  when:
    - (vga_devices_output.stdout.find('AMD') != -1)
    - (isgui | bool)
