- name: install dell command configure
  pacman: name=dell-command-configure state=present update_cache=yes

- name: tmp method to get effective bios password
  shell: echo {{ bios.oldsetuppwd }} > /tmp134

- name: set setuppwd (attempt using old password)
  shell: "{{ item }}"
  ignore_errors: yes
  loop:
    - /opt/dell/dcc/cctk --setuppwd='{{ bios.setuppwd }}' 
    - /opt/dell/dcc/cctk --valsetuppwd="{{ bios.oldsetuppwd }}" --setuppwd="{{ bios.setuppwd }}"
  when: (isdell | bool)
