---
- name: Create fscache folder 
  file:
    path: /var/cache/fscache
    state: directory
    owner: root
  when: (isgui|bool)
    
- name: Install cachefilesd package
  pacman:
    name: cachefilesd
    state: present
    update_cache: yes
  when: (isgui|bool)


# Need to confirm kernel installed is same as running version
# Or figure out why the pacman hooks to perserve kernel modules aren't working
- name: Load cachefiles module
  command: modprobe cachefiles
  when: (isgui|bool)
  ignore_errors: true

- name: Enable and start cachefiles service
  service:
    name: cachefilesd.service
    state: started
    enabled: yes
  when: (isgui|bool)
  ignore_errors: true

