---
- name: reload systemd
  command: systemctl daemon-reload

- name: debug1
  debug:
    msg: unit {{ item.value.mount[1:] | replace('/', "-") }}.mount

- name: Enable systemd mount
  systemd:
    name="{{ item.value.mount[1:] | replace('/', "-") }}.mount"
    state=started
    enabled=true
  with_dict: "{{ mounts }}"
  notify: reload systemd

- name: Enable systemd automount
  systemd:
    name="{{ item.value.mount[1:] | replace('/', "-") }}.automount"
    state=started
    enabled=true
  with_dict: "{{ mounts }}"
  notify: reload systemd

- name: Enable systemd mount_old
  command: systemctl enable  "{{ item.value.mount[1:] | replace('/', "-") }}.mount"
  with_dict: "{{ mounts }}"
  notify: Start systemd mount
  when: item.value.automount == false

- name: Start systemd mount
  command: systemctl start  "{{ item.value.mount[1:] | replace('/', "-") }}.mount"
  with_dict: "{{ mounts }}"
  notify: reload systemd
  when: item.value.automount == false


- name: Enable systemd automount_old
  command: systemctl enable  "{{ item.value.mount[1:] | replace('/', "-") }}.automount"
  with_dict: "{{ mounts }}"
  notify: Start systemd automount
  when: item.value.automount == true

- name: Start systemd automount
  command: systemctl start  "{{ item.value.mount[1:] | replace('/', "-") }}.automount"
  with_dict: "{{ mounts }}"
  notify: reload systemd
  when: item.value.automount == true
