# TODO: remove mkosi suffix or move to variable
- name: Build lasest image from mkosi config
  block:
    - file: path=/data state=directory
    - pacman: name="mkosi-git" state=latest update_cache=true
    - git: repo="{{ arch.mkosi.repo }}" dest="{{ arch.mkosi.dest }}"
    - copy: src=DB.key dest="{{ arch.mkosi.key }}"
    - copy: src=DB.crt dest="{{ arch.mkosi.crt }}"
    - command: "/usr/bin/mkosi --output={{ arch.mkosi.output }} build"
      args: chdir="{{ arch.mkosi.dest }}"
    - command: "mksquashfs {{ arch.mkosi.output }} {{ destination }}/airootfs.sfs"
    - command: "sbsign --key {{ arch.mkosi.key }} --cert {{ arch.mkosi.crt }} --output {{ output }}/linux.signed"
    - copy: src="{{ arch.mkosi.output}}/boot/initramfs-linux.img" dest="{{ output }}/initramfs-linux.img"
